version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:14.17.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@8.6.0"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test
      - run:
          name: build-project
          command: npm run generate:gh-pages
      - store_artifacts:
          path: test-results.xml
          destination: tests
      - store_test_results:
          path: test-results.xml
  deploy-to-github-pages:
    working_directory: ~/project
    docker:
      - image: circleci/node:14.17.4
    steps:
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages --save-dev
            git config user.email "68751170+archimeid@users.noreply.github.com"
            git config user.name "archimeid"
      - run:
          name: Deploy docs to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy-to-github-pages:
          filters:
            branches:
              only: main